"""This module provides script command values."""

PYTHON_INDEX = 1

SC_METHOD_RESPONSE = 1
SC_TERMINATE_SCRIPT = 2
SC_EVENT_CALLBACK = 3
SC_PAUSE_SCRIPT = 4
SC_LANG_VERSION = 5

SC_ADD_TO_SYSTEM_JOURNAL = 10

SC_CLEAR_SYSTEM_JOURNAL = 346
